[package]
name = "rs-rtps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
mio = { version = "0.8.6", features = ["os-poll", "net"]}
rand = "0.8.5"
socket2 = "0.4.7"
speedy = "0.8.5"
