services:
    publisher:
        build:
            context: ..
            dockerfile: dds-analysis-docker/publisher/Dockerfile
            network: host
        image: publisher_img
        container_name: dds_pub
        networks:
            docker-pcap:
                ipv4_address: 192.168.208.2
        tty: true
        command: /bin/bash
        environment:
          DISPLAY: $DISPLAY
        user: foo
        volumes:
            - ../../target:/home/UmberDDS/target
            -  /tmp/.X11-unix/:/tmp/.X11-unix
    publisher2:
        depends_on:
            - publisher
        image: publisher_img
        container_name: dds_pub2
        networks:
            docker-pcap:
                ipv4_address: 192.168.208.4
        tty: true
        command: /bin/bash
        environment:
          DISPLAY: $DISPLAY
        user: foo
        volumes:
            - ../../target:/home/UmberDDS/target
            -  /tmp/.X11-unix/:/tmp/.X11-unix
    subscriber:
        build:
            context: .
            dockerfile: subscriber/Dockerfile
            network: host
        image: subscriber_img
        container_name: dds_sub
        networks:
            docker-pcap:
                ipv4_address: 192.168.208.3
        tty: true
        command: /bin/bash
        volumes:
            - ../RustDDS:/home/RustDDS
            - ../../target:/home/UmberDDS/target
            - ./subscriber/rust-subscriber:/home/rust-subscriber
    subscriber2:
        depends_on:
            - subscriber
        image: subscriber_img
        container_name: dds_sub2
        networks:
            docker-pcap:
                ipv4_address: 192.168.208.5
        tty: true
        command: /bin/bash
        volumes:
            - ../RustDDS:/home/RustDDS
            - ../../target:/home/UmberDDS/target
            - ./subscriber/rust-subscriber:/home/rust-subscriber


networks:
    docker-pcap:
        name: docker-pcap
        external: true
